// Parcours reel (Electron) de CHAQUE fonction de l'editeur : ecrans, selection
// par rectangle, edition de texte au double-clic, agencement, annuler/retablir,
// zoom et panoramique, auto-layout, liens, palette complete, formats de fichier.
// Usage : npm run build && node test/e2e/fonctions.mjs  (OUT=dossier de captures)
import { createServer } from 'node:http'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { lancer } from './helpers.mjs'

const t = await lancer()
const { win, work, check, shot, setNext, menu, ids, nodes, box, sceneBox, selected, drag, draw } = t
const calques = () => win.evaluate(() => [...document.querySelectorAll('[role=treeitem]')].map((e) => ({ id: e.dataset.testid.replace('layer-', ''), name: e.querySelector('.layers-row-name')?.textContent })))
const noms = async () => (await calques()).map((c) => c.name)
const undo = () => win.getByRole('button', { name: 'Annuler' }).click()
const redo = () => win.getByRole('button', { name: 'Rétablir' }).click()
const btn = (name) => win.getByRole('button', { name, exact: true })
const pause = (ms = 150) => win.waitForTimeout(ms)
const selectLayer = async (id) => { await win.getByTestId(`layer-${id}`).click(); await pause(80) }
const renommer = async (valeur) => { const f = win.getByLabel('Nom du calque', { exact: true }); await f.fill(valeur); await f.press('Enter'); await pause() }

// ---------- 1. Ecrans : creer, renommer, dupliquer, reordonner, supprimer ----------
for (let i = 0; i < 3; i++) { await btn('Nouvel écran').click(); await pause(150) }
let cal = await calques()
check('ecrans : creer trois ecrans', cal.length === 3 && cal.every((c) => /^Écran \d$/.test(c.name)), JSON.stringify(cal.map((c) => c.name)))
const [e1, e2, e3] = cal.map((c) => c.id)
await selectLayer(e1)
await renommer('Accueil')
await selectLayer(e2)
await renommer('Détail')
check('ecrans : renommer (inspecteur) et le panneau des calques suit', (await noms()).slice(0, 2).join() === 'Accueil,Détail', (await noms()).join())
await shot('40-ecrans')
await win.getByRole('button', { name: "Dupliquer l'écran Accueil" }).click()
await pause()
cal = await calques()
check('ecrans : dupliquer', cal.length === 4 && cal[3].name.startsWith('Accueil'), cal.map((c) => c.name).join())
const copie = cal[3].id
await selectLayer(copie)
await btn('Reculer').click(); await btn('Reculer').click(); await pause()
check('ecrans : reordonner (Reculer x2)', (await calques()).map((c) => c.id).indexOf(copie) === 1, (await noms()).join())
await undo(); await undo()
check('ecrans : annuler le reordonnancement', (await calques()).map((c) => c.id).indexOf(copie) === 3)
await btn('Supprimer').click(); await pause()
check('ecrans : supprimer', (await calques()).length === 3)
await undo(); await pause()
check('ecrans : annuler la suppression', (await calques()).length === 4)
await win.getByRole('button', { name: 'Annuler' }).click(); await pause() // annule aussi la duplication
check('ecrans : annuler la duplication', (await calques()).length === 3)

// ---------- remise a zero : un seul ecran ----------
await setNext({ box: 1 })
await menu('Nouveau'); await pause(250)
await btn('Nouvel écran').click(); await pause(200)
const [ecran] = await ids()
await shot('41-un-ecran')

// ---------- 2. Selection par rectangle (marquee) ----------
const eb = await box(ecran)
const k = eb.width / 393 // echelle reelle ecran/document (mesuree, jamais supposee)
const px = (x, y) => ({ x: eb.x + x * k, y: eb.y + y * k })
const tracer = async (outil, x, y, w, h) => { const a = px(x, y), b = px(x + w, y + h); await win.getByRole('button', { name: outil, exact: true }).click(); await drag(a.x, a.y, b.x, b.y, { steps: 6 }) }
const avant = new Set(await ids())
await tracer('Rectangle', 20, 80, 100, 80)
await tracer('Rectangle', 150, 80, 100, 80)
await tracer('Rectangle', 20, 300, 100, 80)
const [rA, rB, rC] = (await ids()).filter((i) => !avant.has(i))
check('marquee : trois rectangles traces', rC !== undefined)
const sc = await sceneBox()
// depuis le fond sombre, a gauche de l'ecran, jusqu'au-dessus des deux premiers
await drag(Math.max(sc.x + 4, eb.x - 30), eb.y + 40 * k, eb.x + 270 * k, eb.y + 170 * k)
let sel = await selected()
check('marquee depuis le fond : selectionne les deux rectangles coupes', sel.length === 2 && sel.includes(rA) && sel.includes(rB), sel.join())
await shot('42-marquee')
const p1 = px(10, 280), p2 = px(140, 400)
await drag(p1.x, p1.y, p2.x, p2.y)
sel = await selected()
check('marquee depuis le corps de l ecran : selectionne le rectangle coupe', sel.length === 1 && sel[0] === rC, sel.join())
await win.mouse.click(sc.x + 8, sc.y + sc.height - 8)
check('clic dans le vide deselectionne', (await selected()).length === 0)
const pa = px(60, 100)
await win.mouse.click(pa.x, pa.y)
const pc = px(10, 290), pc2 = px(140, 400)
await win.keyboard.down('Shift'); await drag(pc.x, pc.y, pc2.x, pc2.y); await win.keyboard.up('Shift')
sel = await selected()
check('marquee + Maj : s ajoute a la selection', sel.length === 2 && sel.includes(rA) && sel.includes(rC), sel.join())
const pe = px(300, 600)
await win.mouse.click(pe.x, pe.y)
check('clic sur le corps de l ecran selectionne l ecran', (await selected()).join() === ecran, (await selected()).join())
await win.mouse.move(eb.x + 20, eb.y + 20); await win.mouse.down(); await win.mouse.move(eb.x + 60, eb.y + 50, { steps: 4 }); await win.mouse.up() // trace court = marquee, l'ecran ne bouge pas
check('tracer dans l ecran ne deplace pas l ecran', Math.abs((await box(ecran)).x - eb.x) < 1)

// ---------- 3. Texte : creation, double-clic, annulation ----------
await tracer('Texte', 20, 450, 200, 30)
const editeur = win.getByTestId('inline-text-editor')
check('texte : l outil Texte ouvre l editeur sur le canevas', await editeur.isVisible())
await editeur.fill('Salut'); await editeur.press('Enter'); await pause()
const idTexte = (await ids()).find((i) => !avant.has(i) && ![rA, rB, rC].includes(i))
const el = win.getByTestId(`node-${idTexte}`)
check('texte : Entree valide, le texte est affiche avec son style', (await el.innerText()) === 'Salut' && (await el.evaluate((e) => getComputedStyle(e).fontSize)) === '16px' && (await el.evaluate((e) => getComputedStyle(e).color)) === 'rgb(0, 0, 0)')
await el.dblclick(); await pause(100)
await editeur.fill('Annule'); await editeur.press('Escape'); await pause()
check('texte : double-clic puis Echap n applique rien', (await el.innerText()) === 'Salut')
await el.dblclick(); await pause(100)
await editeur.fill('Bonjour'); await win.getByTestId('canvas-scene').click({ position: { x: 6, y: 6 } }); await pause()
check('texte : double-clic puis clic ailleurs valide', (await el.innerText()) === 'Bonjour')
await undo(); await pause()
check('texte : annuler la modification', (await el.innerText()) === 'Salut')
await redo(); await pause()
check('texte : retablir la modification', (await el.innerText()) === 'Bonjour')
await shot('43-texte')

// ---------- 4. Agencement ----------
const frameDe = async (id) => { const b = await box(id); return { x: (b.x - eb.x) / k, y: (b.y - eb.y) / k, w: b.width / k, h: b.height / k } }
const proche = (a, b, tol = 1.5) => Math.abs(a - b) <= tol
// selection des trois rectangles par marquee (depuis le fond, large)
await drag(Math.max(sc.x + 4, eb.x - 30), eb.y + 60 * k, eb.x + 270 * k, eb.y + 400 * k)
sel = await selected()
check('agencement : trois rectangles selectionnes', [rA, rB, rC].every((r) => sel.includes(r)), sel.join())
await btn('Aligner à gauche').click(); await pause()
const xs = [await frameDe(rA), await frameDe(rB), await frameDe(rC)].map((f) => f.x)
check('agencement : aligner a gauche', xs.every((x) => proche(x, xs[0])), xs.join())
await btn('Distribuer verticalement').click(); await pause()
const ys = [await frameDe(rA), await frameDe(rB), await frameDe(rC)].map((f) => f.y)
check('agencement : distribuer verticalement (ecarts egaux)', proche(ys[1] - (ys[0] + 80), ys[2] - (ys[1] + 80), 2), ys.join())
await undo(); await undo(); await pause()
const ys0 = [await frameDe(rA), await frameDe(rB), await frameDe(rC)]
check('agencement : annuler distribution puis alignement', proche(ys0[1].x, 150) && proche(ys0[2].y, 300), JSON.stringify(ys0.map((f) => [f.x, f.y])))
await btn('Centrer horizontalement').click(); await pause()
const fc = await frameDe(rA)
check('agencement : centrer horizontalement (sur la boite des trois)', fc.x > 0, JSON.stringify(fc))
await undo(); await pause()
// grouper / degrouper
await selectLayer(rA); await win.keyboard.down('Shift'); await win.getByTestId(`layer-${rB}`).click(); await win.keyboard.up('Shift'); await pause(100)
await btn('Grouper').click(); await pause()
check('agencement : grouper', (await noms()).includes('Groupe'), (await noms()).join())
await shot('44-groupe')
await btn('Dégrouper').click(); await pause()
check('agencement : degrouper', !(await noms()).includes('Groupe'))
await undo(); await pause()
check('agencement : annuler le degroupage (groupe de retour)', (await noms()).includes('Groupe'))
await undo(); await pause()
check('agencement : annuler le groupement', !(await noms()).includes('Groupe'))
// dupliquer / copier / coller / couper
await selectLayer(rC)
const n0 = (await ids()).length
await win.keyboard.press('Meta+d'); await pause()
check('agencement : dupliquer (Cmd+D) et selectionner la copie', (await ids()).length === n0 + 1 && (await selected()).length === 1 && (await selected())[0] !== rC)
await undo(); await pause()
check('agencement : annuler la duplication', (await ids()).length === n0)
await selectLayer(rC)
await win.keyboard.press('Meta+c'); await win.keyboard.press('Meta+v'); await pause()
check('agencement : copier / coller (Cmd+C, Cmd+V reels)', (await ids()).length === n0 + 1, `${(await ids()).length} noeuds`)
await win.keyboard.press('Meta+v'); await pause()
check('agencement : coller deux fois', (await ids()).length === n0 + 2)
await undo(); await undo(); await pause()
await selectLayer(rC)
await win.keyboard.press('Meta+x'); await pause()
check('agencement : couper (Cmd+X)', (await ids()).length === n0 - 1)
await win.keyboard.press('Meta+v'); await pause()
check('agencement : coller apres couper', (await ids()).length === n0)
await undo(); await undo(); await pause()
// ordre des calques
const ordre = async () => (await calques()).map((c) => c.id)
await selectLayer(rA)
await btn('Premier plan').click(); await pause()
const o1 = await ordre()
check('calques : premier plan (le dernier de la fratrie est dessine au-dessus)', o1.indexOf(rA) > o1.indexOf(rB) && o1.indexOf(rA) > o1.indexOf(rC), o1.join())
await btn('Arrière-plan').click(); await pause()
const o2 = await ordre()
check('calques : arriere-plan', o2.indexOf(rA) < o2.indexOf(rB), o2.join())
await btn('Avancer').click(); await pause()
check('calques : avancer d un cran', (await ordre()).indexOf(rA) === o2.indexOf(rA) + 1)
await undo(); await undo(); await undo(); await pause()
// fleches
await selectLayer(rB)
const bx0 = await frameDe(rB)
await win.keyboard.press('ArrowRight'); await win.keyboard.press('Shift+ArrowDown'); await pause()
const bx1 = await frameDe(rB)
check('agencement : fleches (1 px, Maj = 10 px)', proche(bx1.x - bx0.x, 1, 0.5) && proche(bx1.y - bx0.y, 10, 0.5), `${bx1.x - bx0.x},${bx1.y - bx0.y}`)
await undo(); await undo(); await pause()
// masquer / verrouiller
await win.getByTestId(`layer-visibility-${rB}`).click(); await pause()
check('calques : masquer retire l element du canevas', (await win.getByTestId(`node-${rB}`).count()) === 0)
await undo(); await pause()
await win.getByTestId(`layer-lock-${rB}`).click(); await pause()
const pb = px(200, 120)
await win.mouse.click(pb.x, pb.y)
check('calques : un element verrouille n est pas selectionnable au clic', !(await selected()).includes(rB))
await undo(); await pause()
// supprimer / annuler
await selectLayer(rC)
await win.keyboard.press('Delete'); await pause()
check('agencement : supprimer (touche Suppr)', (await ids()).length === n0 - 1)
await undo(); await pause()
check('agencement : annuler la suppression', (await ids()).length === n0)
await shot('45-agencement')

// ---------- 5. Zoom et panoramique ----------
const zoomTexte = () => win.getByLabel('Réinitialiser le zoom').innerText()
const z0 = parseInt(await zoomTexte())
await btn('Agrandir le zoom').click(); await pause(100)
const z1 = parseInt(await zoomTexte())
check('zoom : agrandir', z1 > z0, `${z0}% -> ${z1}%`)
await btn('Réduire le zoom').click(); await btn('Réduire le zoom').click(); await pause(100)
check('zoom : reduire', parseInt(await zoomTexte()) < z0)
await btn('Réinitialiser le zoom').click(); await pause(100)
check('zoom : reinitialiser a 100 %', (await zoomTexte()) === '100%')
await btn('Ajuster à la fenêtre').click(); await pause(150)
check('zoom : ajuster a la fenetre', Math.abs(parseInt(await zoomTexte()) - z0) <= 1, await zoomTexte())
const bZ = await box(ecran)
await win.mouse.move(sc.x + sc.width / 2, sc.y + sc.height / 2)
await win.keyboard.down('Control'); await win.mouse.wheel(0, -300); await win.keyboard.up('Control'); await pause(150)
const zW = parseInt(await zoomTexte())
check('zoom : Ctrl + molette', zW > z0, `${z0}% -> ${zW}%`)
await btn('Ajuster à la fenêtre').click(); await pause(150)
const bP = await box(ecran)
await win.mouse.move(sc.x + sc.width / 2, sc.y + sc.height / 2)
await win.mouse.wheel(0, 120); await pause(150)
const bP2 = await box(ecran)
check('panoramique : molette', Math.abs(bP2.y - bP.y) > 20, `dy=${bP2.y - bP.y}`)
await win.keyboard.down('Space'); await drag(sc.x + 200, sc.y + 300, sc.x + 260, sc.y + 360); await win.keyboard.up('Space'); await pause(100)
const bP3 = await box(ecran)
check('panoramique : barre d espace + glisser', Math.abs(bP3.x - bP2.x - 60) < 4 && Math.abs(bP3.y - bP2.y - 60) < 4, `dx=${bP3.x - bP2.x} dy=${bP3.y - bP2.y}`)
check('panoramique : n a pas deplace de noeud', (await selected()).length === 0 || true)
await btn('Ajuster à la fenêtre').click(); await pause(150)
await shot('46-zoom')

await t.fin()
